<div class="container-fluid">
	<div class="row">
		<div class="gift2"></div>
		<div class="col-md-12 well">
			 <form id="form_agregar_cliente" enctype="multipart/form-data" method="post" action="<?php echo BASE_URL ?>servicio/registrar_servicio" > 
			<div class="col-md-12"> <center> <h4> Registro de solicitud de servicio </h4> </center></div>

			<div class="col-md-12 ">
				
				  <div class="form-group row ">
				    	<center> <label for="staticEmail" class="form-label formulario">Pedido e inconveniente.</label> </center>
				    <div>
				      	<textarea class="form-control" id="servicio" name="servicio" autofocus placeholder="Escriba su inconveniente aqui." required="true"></textarea>
				    </div>
				  </div>
				  </div>
				  <div class="col-md-6">
				  <div class="form-group formulario">
             		 	<label class="formulario"><b> Motivo de la atención </b></label>
            
                		<div class="form-check ">
						  <input class="form-check-input" type="checkbox" value="1" name ="software" id="software">
						  <label class="form-check-label formulario" for="defaultCheck1">
						    Mantenimiento de Software
						  </label>
						</div>
						<div class="form-check ">
						  <input class="form-check-input" type="checkbox" value="1" id="hardware" name="hardware">
						  <label class="form-check-label formulario" for="defaultCheck1">
						    Mantenimiento de Hardware
						  </label>
						</div>
						<div class="form-check ">
						  <input class="form-check-input" type="checkbox" value="1" id="funcionamiento" name="funcionamiento">
						  <label class="form-check-label formulario" for="defaultCheck1">
						    Pruebas de Funcionamiento
						  </label>
						</div>

						<div class="form-check ">
						  <input class="form-check-input" type="checkbox" value="1" id="otros" name="otros">
						  <label class="form-check-label formulario" for="defaultCheck1">
						    Otros
						  </label>
						</div>
						<div class="form-group" id="divotros">
						 <textarea id="otrosrespuesta" name="otrosrespuesta" class="form-control" autofocus placeholder="Responda aqui."></textarea>
						</div>


              
          			</div>
				  </div>
				  <div class="col-md-6">
				      	<p><b>Adjuntar imagen/Foto:</b><input type='file' accept='image/*' id='cargar_imagen' name='foto[]' capture='camera'> </p>
				    </div>

				    <div class="col-md-12" id='list'>
				      	<center> <p><b>Previsualización</b></p> </center>
				    </div>

				  <div class="col-md-12">
				
				  <div class="form-group row">
				    	<center> <label for="staticEmail" class="form-label formulario"> <b>Informacion Adicional </b></label> </center>
				  </div>
				  <div class="form-group row col-md-6">
				    	<label class="formulario"> Fecha de la posible atención </label>
				    <div>
				      	<input class="form-control" type="date" min="<?php $hoy=date("Y-m-d"); echo $hoy;?>" id="fecha_atencion" name="fecha_atencion">
				    </div>
				  </div>
				  <div class="form-group row col-md-6">
				    	<label class="formulario"> Hora de la atención  </label>
				    <div>
				      	<input class="form-control" type="time" min="09:00" max="16:00" id="hora_atencion" name="hora_atencion">
				    </div>
				  </div>


			
				 
				    
			
			
						
              
          			</div>

          			<div class="col-md-12"> <center> <button type="submit" id="enviar_solicitud" class="btn btn-default">Enviar Solicitud</button> </center></div>
          			</form>
				  </div>
			
					
			</div>


		</div>


	



		
		
		

