<div class="container-fluid">
	<div class="row well">
	<form id="form_agregar_servicio" enctype="multipart/form-data" method="post" action="<?php echo BASE_URL ?>servicio/registrar_servicio" >	
		<div class="col-md-2" style="padding-top: 1%;">
					<input type="hidden" value="<?php echo session::get('role') ?>" id="id_role">
					<center> <a class="bnt btn-default btn-xs" type="submit" href="<?php BASE_URL; ?>solicitudes"> <span class="glyphicon glyphicon-th-list"></span> Mis Solicitudes</a> </center>
				</div>
				<?php if(session::get('role')==1){ ?>
				<div class="col-md-2 col-md-offset-7" style="padding-top: 1%;">
					<p>Seleccione el Usuario</p>
					<select class="form-control" name="id_usuario" id="id_usuario" required="true">
						<option value=''>--Seleccione--</option>
						<?php for ($i=0; $i < count($this->usuarios); $i++): ?>
                		<option value="<?php echo $this->usuarios[$i]['id_usuario'] ?>"><?php echo $this->usuarios[$i]['nombre'].' '.$this->usuarios[$i]['apellido'] ?></option>
                		<?php endfor; ?>
					</select>
				</div>

			<?php } ?>
		<div class="gift2"></div>
		<div class="col-md-12">
			 
			<div class="col-md-12"> <center> <h4> Registro de solicitud de servicio </h4> </center></div>

			<div class="col-md-12 ">
				
				  <div class="form-group row ">
				    	<center> <label for="staticEmail" class="form-label formulario">Pedido e inconveniente.</label> </center>
				    <div>
				      	<textarea class="form-control" id="servicio" name="servicio" autofocus placeholder="Escriba su inconveniente aqui." required="true"></textarea>
				    </div>
				  </div>
				  </div>
				  <div class="col-md-12">
<div class="col-md-12 formulario"><b> <center> Motivo de la atención </center> </b></div>
				  	<label class="checkbox-inline" style="padding: 1%;">
  <input class="form-check-input" type="checkbox" value="1" name ="software" id="software"> Mantenimiento de Software
</label>
<label class="checkbox-inline" style="padding: 1%;">
  <input class="form-check-input" type="checkbox" value="1" id="hardware" name="hardware"> Mantenimiento de Hardware
</label>
<label class="checkbox-inline" style="padding: 1%;">
  <input class="form-check-input" type="checkbox" value="1" id="funcionamiento" name="funcionamiento"> Pruebas de Funcionamiento
</label>
<label class=" checkbox-inline" style="padding: 1%;">
  <input class="form-check-input" type="checkbox" value="1" id="otros" name="otros"> Otros
</label>

						<div class="form-group" id="divotros">
						 <textarea id="otrosrespuesta" name="otrosrespuesta" class="form-control" autofocus placeholder="Responda aqui."></textarea>
						</div>

              
          			</div>
				  
				  <div class="col-md-3" style="padding-top: 3%;">
				      	<p><b>Adjuntar imagen/Foto:</b><input type='file' accept='image/*' multiple="multiple"  min="1" max="3" id='cargar_imagen' name='foto[]' capture='camera'> </p>
				    </div>

				    <div class="col-md-9" id='list' style="padding-top: 3%;">
				      	<center> <p><b>Previsualización</b></p> </center>
				    </div>

				  <div class="col-md-12">
				
				  <div class="form-group row">
				    	<center> <label for="staticEmail" class="form-label formulario"> <b>Informacion Adicional </b></label> </center>
				  </div>
				  <div class="form-group row col-md-6">
				    	<label class="formulario"> Fecha de la posible atención </label>
				    <div>
				      	<input class="form-control" type="date" min="<?php $hoy=date("Y-m-d"); echo $hoy;?>" id="fecha_atencion" name="fecha_atencion">
				    </div>
				  </div>
				  <div class="form-group row col-md-6">
				    	<label class="formulario"> Hora de la atención  </label>
				    <div>
				      	<input class="form-control" type="time" id="hora_atencion" name="hora_atencion">
				    </div>
				  </div>


			
				 
				    
			
			
						
              
          			</div>

          			<div class="col-md-12"> <center> <button type="submit" id="enviar_solicitud" class="btn btn-default">Enviar Solicitud</button> </center></div>
          			</form>
				  </div>
			
					
			</div>


		</div>


	



		
		
		

