</div class="container"> 

		

<center><h3> MI INFORMACION</h3></center>

<div class="col-md-12">

            <div class="panel with-nav-tabs panel-primary">
                <div class="panel-heading">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1primary" data-toggle="tab"> <i class="glyphicon glyphicon-user"> </i> General</a></li>
                            <li><a href="#tab2primary" data-toggle="tab"><i class=" glyphicon glyphicon-info-sign"> </i> Adicional</a></li>
                            <li><a href="#tab3primary" data-toggle="tab"> <i class="glyphicon glyphicon-user"> </i> Familiares</a></li>
                            <li><a href="#tab4primary" data-toggle="tab"> <i class="glyphicon glyphicon-random"> </i> Direcciones</a></li>
                            <li><a href="#tab5primary" data-toggle="tab">  <i class="glyphicon glyphicon-alert"> </i> Emergencias</a></li>
                            <li><a href="#tab6primary" data-toggle="tab"> <i class="glyphicon glyphicon-plus"> </i>  Ficha Medica</a></li>
                            <li><a href="#tab7primary" data-toggle="tab"> <i class="glyphicon glyphicon-calendar"> </i> Rutas</a></li>
                            <li><a href="#tab8primary" data-toggle="tab"> <i class="glyphicon glyphicon-calendar"> </i>  Año</a></li>
                           
                        </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1primary">

                            <table class="table">
  <tbody>
    <tr>

      <td>Cedula/Pasaporte:</td>
      <td>23347026</td>

    </tr>
    <tr>

      <td>Nombres:</td>
      <td>Gilberto Luis</td>

    </tr>
    <tr>

      <td>Apellidos:</td>
      <td>Vargas Ramos</td>

    </tr>

    <tr>

      <td>Fecha de Nacimiento:</td>
      <td>12/08/1992</td>

    </tr>

    <tr>

      <td>Correo Electronico:</td>
      <td>Ticox.Vargas@Gmail.com</td>

    </tr>

    <tr>

      <td>Telefono:</td>
      <td>0979348022</td>

    </tr>
  </tbody>
</table>


                        </div>
                        <div class="tab-pane fade" id="tab2primary">
                            
                              <table class="table">
  <tbody>
    <tr>

      <td>Nacionalidad:</td>
      <td>Venezolano</td>

    </tr>
    <tr>

      <td>Lugar de Nacimiento:</td>
      <td>Cumaná</td>

    </tr>
    <tr>

      <td>Institución anterior:</td>
      <td></td>

    </tr>

    <tr>

      <td>Razones para el cambio</td>
      <td></td>

    </tr>

  </tbody>
</table>



                        </div>
                        <div class="tab-pane fade" id="tab3primary">
                            

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Familiar</th>
      <th scope="col">Relacion</th>
      <th scope="col">Repr. Legal?</th>
      <th scope="col">Repr. Economico?</th>
      <th scope="col">Puede retirar</th>
      <th scope="col">Vive con</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Yomarina Ramos</td>
      <td>Madre</td>
      <td>Si</td>
      <td>No</td>
      <td>Si</td>
      <td>Si</td>
    </tr>
    
  </tbody>
</table>







                        </div>
                        <div class="tab-pane fade" id="tab4primary">
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Direccion</th>
      <th scope="col">L</th>
      <th scope="col">M</th>
      <th scope="col">M</th>
      <th scope="col">J</th>
      <th scope="col">V</th>
      <th scope="col">S</th>
      <th scope="col">D</th>
      <th scope="col">Principal</th>
     
     
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
     
    </tr>
    
  </tbody>
</table>

                        </div>
                        <div class="tab-pane fade" id="tab5primary">

                            <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Familiar</th>
      <th scope="col">Relacion</th>
      <th scope="col">Celular</th>
      <th scope="col">Casa?</th>
      <th scope="col">Trabajo</th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>-</th>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      
    </tr>
    
  </tbody>
</table>

                            
                        </div>
                        <div class="tab-pane fade" id="tab6primary">
                            

        <div class="panel with-nav-tabs panel-primary">
                <div class="panel-heading">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1daprimary" data-toggle="tab">  Datos Generales</a></li>
                            <li><a href="#tab2daprimary" data-toggle="tab"> Enfermendades</a></li>
                            <li><a href="#tab3daprimary" data-toggle="tab">  Alergias</a></li>
                            <li><a href="#tab4daprimary" data-toggle="tab">  Vacunas</a></li>
                            <li><a href="#tab5daprimary" data-toggle="tab">  Observaciones</a></li>                          
                        </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1daprimary">

                         <table class="table">
  <thead>
    <tr>
      <th scope="col">Altura</th>
      <th scope="col">Peso</th>
      <th scope="col">Tipo de Sangre</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>


                        </div>
                        <div class="tab-pane fade" id="tab2daprimary">
                            
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Enfermedad</th>
      <th scope="col">Tuvo/Tiene</th>
      <th scope="col">Descripcion/Tratamiento</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>



                        </div>
                        <div class="tab-pane fade" id="tab3daprimary">
                            

   <table class="table">
  <thead>
    <tr>
      <th scope="col">Tipo de alergia</th>
      <th scope="col">Nombre</th>
      <th scope="col">Reacción</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>





                        </div>
                        <div class="tab-pane fade" id="tab4daprimary">
                            
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Fecha</th>
      <th scope="col">Descripción</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>

                        </div>
                        <div class="tab-pane fade" id="tab5daprimary">
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Observaciones</th>
     
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
     
    </tr>
    
  </tbody>
</table>
                        </div>
                        
                    </div>
                </div>
            </div>















                        </div>
                        <div class="tab-pane fade" id="tab7primary">
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Ruta</th>
      <th scope="col">Descripción</th>
      <th scope="col">L</th>
      <th scope="col">M</th>
      <th scope="col">M</th>
      <th scope="col">J</th>
      <th scope="col">V</th>
      <th scope="col">S</th>
      <th scope="col">D</th>
     
     
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
     
    </tr>
    
  </tbody>
</table>
                        </div>
                        <div class="tab-pane fade" id="tab8primary">
                              <table class="table">
  <tbody>
    <tr>

      <td>Curso:</td>
      <td>-</td>

    </tr>
    <tr>

      <td>Paralelo:</td>
      <td>-</td>

    </tr>
    <tr>

      <td>Inscrito:</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Matriculado:</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Tipo de Matricula:</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Retirado</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Fecha de matriculación</td>
      <td>-</td>

    </tr>
  </tbody>
</table>
                        </div>
                    </div>
                </div>
            </div>
	</div>

</div>