<div class="container-fluid">
	<div class="gift2"></div>
	<div class="row">
	
			<div class="col-md-12"> <center> <h4> Solicitudes Pendientes </h4> </center></div>
			
			<div class="col-md-12">
				
<div class="table-responsive">
				<table class="table table-responsive">
					  <thead class="thead-dark">
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Empresa</th>
					      <th scope="col">Usuario</th>
					      <th scope="col">Servicio</th>
					      <th scope="col">Fecha de Solicitud</th>
					      <th scope="col">Fecha Tentativa</th>
					      <th scope="col">Estatus</th>
					      <th scope="col">Acciones</th>
					    </tr>
					  </thead>
					  <tbody>
					   <?php if(count($this->servicio)==''){?>

					   	<tr>
		<th colspan="8"><h4> <center> No hay solicitudes pendientes </center> </h4></th>

					 <?php  }else{ ?>
					    	<?php for ($i=0; $i < count($this->servicio); $i++): ?>
		<tr>

			<?php if($this->servicio[$i]['fecha_atencion']==""){
				$newDate2 = "No se definió";}
				else{ $newDate2 = date("d/m/Y", strtotime($this->servicio[$i]['fecha_atencion'])); }?>
			<?php $newDate = date("d/m/Y", strtotime($this->servicio[$i]['fecha']));?>
		<th><?php echo ($i+1); ?></th>
		<td><?php echo $this->servicio[$i]['empresa'] ?></td>
		<td><?php echo $this->servicio[$i]['nombre'].' '.$this->servicio[$i]['apellido'] ?></td>
		<td><?php echo substr($this->servicio[$i]['pedido'], 0, 50).' ...'; ?></td>
		<td><?php echo $newDate." ".$this->servicio[$i]['hora']  ?></td>
		<td><?php echo $newDate2." ".$this->servicio[$i]['hora_atencion'] ?></td>		
		<?php if($this->servicio[$i]['estatus']=='pendiente'){ ?>
		<td class="offline">Pendiente</td>
	<?php  } else { ?>
		<td class="online">Solucionado</td>
			<?php  } ?>
			<td><a href="javascript:null()"  data-toggle="modal" data-target="#modalcambiar" id="cambiar_estatus" data-id_servicio="<?php echo $this->servicio[$i]['id_servicio'] ?>"> <i class="glyphicon glyphicon-pencil"> </i> Cambiar Estatus </a></td>
		</tr>
		<?php endfor; ?>
	<?php  } ?>
					  
					  </tbody>
					</table>

				</div>	
			</div>


		</div>

		<div class="row">
	
			<div class="col-md-12"> <center> <h4> Solicitudes Resueltas </h4> </center></div>
					<div class="col-xs-12 col-md-6 col-md-offset-3">
				<i for="exampleInputEmail1">Buscar Servicios por Nombre de Usuarios</i>
				<center><input class="form-control" type="text" id="buscar_servicio_s"></center>
			</div>
			<div class="col-md-12 table-responsive" id="div_contenedor">
				  <table class="table ">
					  <thead class="thead-dark">
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Empresa</th>
					      <th scope="col">Usuario</th>
					      <th scope="col">Servicio</th>
					      <th scope="col">Fecha de Solución</th>
					      <th scope="col">Hora</th>
					      <th scope="col">Estatus</th>
					      <th scope="col">Acciones</th>
					    </tr>
					  </thead>
					  <tbody>
					   <?php if(count($this->servicio_r)==''){?>

					   	<tr>
		<th colspan="8"><h4> <center> No hay solicitudes solucionadas </center> </h4></th>

					 <?php  }else{ ?>
					    	<?php for ($i=0; $i < count($this->servicio_r); $i++): ?>
		<tr>
		<th><?php echo ($i+1); ?></th>
		<td><?php echo $this->servicio_r[$i]['empresa'] ?></td>
		<td><?php echo $this->servicio_r[$i]['nombre'].' '.$this->servicio_r[$i]['apellido'] ?></td>
		<td><?php echo substr($this->servicio_r[$i]['pedido'], 0, 50).' ...'; ?></td>
		<td><?php echo $newDate = date("d/m/Y", strtotime($this->servicio_r[$i]['fecha_inicio'])); ?></td>
		<td><?php echo $this->servicio_r[$i]['hora_inicio'] ?></td>	
		<?php if($this->servicio_r[$i]['estatus']=='pendiente'){ ?>
		<td class="offline">Pendiente</td>
	<?php  } else { ?>
		<td class="online">Solucionado</td>
			<?php  } ?>
			<td><a href="javascript:null()"  data-toggle="modal" data-target="#modalservicio" id="detalles_servicio" data-id_servicio="<?php echo $this->servicio_r[$i]['id_servicio'] ?>"> <i class="glyphicon glyphicon-list"> </i> Detalles </a> <a href="javascript:null()"  data-toggle="modal" data-target="#modaleservicio" id="editar_servicio_s" data-id_servicio="<?php echo $this->servicio_r[$i]['id_servicio'] ?>"> <i class="glyphicon glyphicon-pencil"> </i> Editar </a></td>
		</tr>
		<?php endfor; ?>
		<?php  } ?>
					  
					  </tbody>
					</table>
				

					
			</div>


		</div>


	</div>


<div class="modal fade" id="modalcambiar" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel"><center>Cambiar estatus de solicitud</center></h3>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="form_agregar_cliente" enctype="multipart/form-data" method="post" action="<?php echo BASE_URL ?>admin_servicios/cambiar_estatus_servicio" >
      <div class="modal-body" id="ver_servicio_pendiente">
         <h3> <center> Cargando... </center></h3>
      </div>
  	
      <div class="gift2"></div>
      <div class="modal-footer">
        <button type="" id="cambiar_estatus_servicios" class="btn btn-default">Guardar Cambios</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
      </form>
    </div>
  </div>
</div>


<div class="modal fade" id="modalservicio" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel"><center>Servicio Solucionado</center></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="ver_servicio">
         <h3> <center> Cargando... </center></h3>
      </div>
      <div class="modal-footer">
        <button type="button" id="reenviar_correo" class="btn btn-default">Reenviar Correo</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="modaleservicio" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel"><center>Editar Servicio</center></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="e_servicio_s">
         <h3> <center> Cargando... </center></h3>
      </div>
      <div class="modal-footer" style="padding-top: 1%;">
        <button type="button" id="guardar_servicio_modificado" class="btn btn-default">Guardar Cambios</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


		
		
		

