
<div class="col-md-8 col-md-offset-2 xx">
	<div class="col-md-8 col-md-offset-2">Panel de control</div>
	<div class="col-md-8 col-md-offset-2 panel-title">
	<div class="col-md-12">
		<center> Registros </center>
	</div>
	<div>
	<center> <a href="<?php echo BASE_URL ?>registro/nenas">Publicacion</a> </center>
	</div>
	<div class="col-md-8 col-md-offset-2">
	<center> <a href="<?php echo BASE_URL ?>registro/agencias">Agencias</a> </center>
	</div>
	</div>
	
</div>
