</div class="container"> 

		

<center><h3> CARGAR MI INFORMACIÓN</h3></center>

<div class="col-md-12">

            <div class="panel with-nav-tabs panel-primary">
                <div class="panel-heading">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1primary" data-toggle="tab"> <i class="glyphicon glyphicon-user"> </i> General</a></li>
                            <li><a href="#tab2primary" data-toggle="tab"><i class=" glyphicon glyphicon-info-sign"> </i> Adicional</a></li>
                            <li><a href="#tab3primary" data-toggle="tab"> <i class="glyphicon glyphicon-user"> </i> Familiares</a></li>
                            <li><a href="#tab4primary" data-toggle="tab"> <i class="glyphicon glyphicon-random"> </i> Direcciones</a></li>
                            <li><a href="#tab5primary" data-toggle="tab">  <i class="glyphicon glyphicon-alert"> </i> Emergencias</a></li>
                            <li><a href="#tab6primary" data-toggle="tab"> <i class="glyphicon glyphicon-plus"> </i>  Ficha Medica</a></li>
                            <li><a href="#tab7primary" data-toggle="tab"> <i class="glyphicon glyphicon-calendar"> </i> Rutas</a></li>
                            <li><a href="#tab8primary" data-toggle="tab"> <i class="glyphicon glyphicon-calendar"> </i>  Año</a></li>
                           
                        </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1primary">

                            <table class="table">
  <tbody>
    <tr>

      <td>Cedula/Pasaporte:<input type="text" class="form-control" id="cedula" name="cedula" placeholder="Cedula"></td>
      <td>Fecha de Nacimiento:<input type="date" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" placeholder="fecha de nacimiento"></td>

    </tr>
    <tr>

      <td>Nombres: <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombres"></td>
      <td>Apellidos:<input type="text" class="form-control" id="apellidos" name="apellidos" placeholder="Apellidos"></td>

    </tr>
    
  
  </tbody>
</table>

<center> <button type="button" id="guardar_menu" class="btn btn-default">Registrar</button> </center>

                        </div>
                        <div class="tab-pane fade" id="tab2primary">

                          <table class="table">
  <tbody>
    <tr>

      <td>Nacionalidad:<input type="text" class="form-control" id="nacionalidad" name="nacionalidad" placeholder="Nacionalidad"></td>
      <td>Lugar de Nacimiento:<input type="date" class="form-control" id="lugar_nacimiento" name="lugar_nacimiento" placeholder="Lugar de Nacimiento"></td>

    </tr>
    <tr>

      <td>Institución anterior: <input type="text" class="form-control" id="ins_anterior" name="ins_anterior" placeholder="Institución anterior: "></td>
      <td>Razones para el cambio:<input type="text" class="form-control" id="razon_cambio" name="razon_cambio" placeholder="Razones para el cambio:"></td>

    </tr>
    
  
  </tbody>
</table>

<center> <button type="button" id="guardar_menu" class="btn btn-default">Registrar</button> </center>


                        </div>
                        <div class="tab-pane fade" id="tab3primary">
                            
<center> Pesar como agregar los familiares de manera optima.</center>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Familiar</th>
      <th scope="col">Relacion</th>
      <th scope="col">Repr. Legal?</th>
      <th scope="col">Repr. Economico?</th>
      <th scope="col">Puede retirar</th>
      <th scope="col">Vive con</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Yomarina Ramos</td>
      <td>Madre</td>
      <td>Si</td>
      <td>No</td>
      <td>Si</td>
      <td>Si</td>
    </tr>
    
  </tbody>
</table>







                        </div>
                        <div class="tab-pane fade" id="tab4primary">
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Direccion</th>
      <th scope="col">L</th>
      <th scope="col">M</th>
      <th scope="col">M</th>
      <th scope="col">J</th>
      <th scope="col">V</th>
      <th scope="col">S</th>
      <th scope="col">D</th>
      <th scope="col">Principal</th>
     
     
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
     
    </tr>
    
  </tbody>
</table>

                        </div>
                        <div class="tab-pane fade" id="tab5primary">

                            <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Familiar</th>
      <th scope="col">Relacion</th>
      <th scope="col">Celular</th>
      <th scope="col">Casa?</th>
      <th scope="col">Trabajo</th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>-</th>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      
    </tr>
    
  </tbody>
</table>

                            
                        </div>
                        <div class="tab-pane fade" id="tab6primary">
                            

        <div class="panel with-nav-tabs panel-primary">
                <div class="panel-heading">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1daprimary" data-toggle="tab">  Datos Generales</a></li>
                            <li><a href="#tab2daprimary" data-toggle="tab"> Enfermendades</a></li>
                            <li><a href="#tab3daprimary" data-toggle="tab">  Alergias</a></li>
                            <li><a href="#tab4daprimary" data-toggle="tab">  Vacunas</a></li>
                            <li><a href="#tab5daprimary" data-toggle="tab">  Observaciones</a></li>                          
                        </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tab1daprimary">

                         <table class="table">
  <thead>
    <tr>
      <th scope="col">Altura</th>
      <th scope="col">Peso</th>
      <th scope="col">Tipo de Sangre</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>


                        </div>
                        <div class="tab-pane fade" id="tab2daprimary">
                            
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Enfermedad</th>
      <th scope="col">Tuvo/Tiene</th>
      <th scope="col">Descripcion/Tratamiento</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>



                        </div>
                        <div class="tab-pane fade" id="tab3daprimary">
                            

   <table class="table">
  <thead>
    <tr>
      <th scope="col">Tipo de alergia</th>
      <th scope="col">Nombre</th>
      <th scope="col">Reacción</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>





                        </div>
                        <div class="tab-pane fade" id="tab4daprimary">
                            
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Fecha</th>
      <th scope="col">Descripción</th>
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
    </tr>
    
  </tbody>
</table>

                        </div>
                        <div class="tab-pane fade" id="tab5daprimary">
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Observaciones</th>
     
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
     
    </tr>
    
  </tbody>
</table>
                        </div>
                        
                    </div>
                </div>
            </div>















                        </div>
                        <div class="tab-pane fade" id="tab7primary">
                            <table class="table">
  <thead>
    <tr>
      <th scope="col">Ruta</th>
      <th scope="col">Descripción</th>
      <th scope="col">L</th>
      <th scope="col">M</th>
      <th scope="col">M</th>
      <th scope="col">J</th>
      <th scope="col">V</th>
      <th scope="col">S</th>
      <th scope="col">D</th>
     
     
 
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
      <td>-</td>
     
    </tr>
    
  </tbody>
</table>
                        </div>
                        <div class="tab-pane fade" id="tab8primary">
                              <table class="table">
  <tbody>
    <tr>

      <td>Curso:</td>
      <td>-</td>

    </tr>
    <tr>

      <td>Paralelo:</td>
      <td>-</td>

    </tr>
    <tr>

      <td>Inscrito:</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Matriculado:</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Tipo de Matricula:</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Retirado</td>
      <td>-</td>

    </tr>

    <tr>

      <td>Fecha de matriculación</td>
      <td>-</td>

    </tr>
  </tbody>
</table>
                        </div>
                    </div>
                </div>
            </div>
	</div>

</div>