
 
<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10  col-xs-offset-1 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
<div class="header-titulos">CAMBIO DE CONTRASEÑA</div>






 <div class="col-xs-10 col-sm-8 col-md-8 col-lg-8 ">


           <div class="form-group ">
              <label class="control-label">CONTRASEÑA ACTUAL</label>
              
                <input type="password" type="text" class="form-control" id="actual" name="actual" required="required">
              
          </div>
          <div class="form-group">
              <label class=" control-label">CONTRASEÑA NUEVA</label>
            
                <input type="password" type="text" class="form-control" id="nueva" name="nueva" required="required">
              
          </div>
          <div class="form-group ">
              <label class=" control-label">CONFIRMAR CONTRASEÑA</label>
          
                <input type="password" type="text" class="form-control" id="confirmar" name="confirmar" required="required">
              
          </div>
            <div class="form-group ">
              <button id="cambiarclave" type="button" class="btn btn-primary btn-sm">CAMBIAR CLAVE</button>
            <button onclick="javascript:history.back()" class="btn btn-primary btn-sm">CANCELAR</button>

          </div>
    
</div>
<div class="col-xs-2 col-sm-4 col-md-4 col-lg-4">
<img src="<?php echo BASE_URL?>/public/img/llave.png" alt=" ">
</div>


</div>