
 
<div class="container-fluid back_cambiar" >
  <div class="row vista_cambiar">
<div class=" col-md-12 titulo-header"> <center> <h3>CAMBIO DE CONTRASEÑA </h3> </center></div>




<div class="col-md-4"></div>

 <div class="col-xs-8 col-sm-6 col-md-4">


           <div class="form-group ">
              <label class="control-label">Contraseña Actual</label>
              
                <input type="password" type="text" class="form-control" id="actual" name="actual" required="required">
              
          </div>
          <div class="form-group">
              <label class=" control-label">Contraseña Nueva</label>
            
                <input type="password" type="text" class="form-control" id="nueva" name="nueva" required="required">
              
          </div>
          <div class="form-group ">
              <label class=" control-label">Confirmar Contraseña</label>
          
                <input type="password" type="text" class="form-control" id="confirmar" name="confirmar" required="required">
              
          </div>
            <div class="form-group ">
              <button id="cambiarclave" type="button" class="btn btn-primary btn-sm">Cambiar</button>
            <button onclick="javascript:history.back()" class="btn btn-primary btn-sm">Cancelar</button>

          </div>

</div>
</div>