	
    <div class="col-xs-10 col-sm-8 col-md-8 col-lg-8  col-xs-offset-1 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">

   <div class="divregistro">RECUPERACIÓN DE CUENTA</div>
       
           <div class="form-group ">
              <label class="control-label">INTRODUZCA SU CORREO, RECIBIRA SU CLAVE MEDIANTE SU EMAIL</label>
             
                <input type="email" type="text" class="form-control" id="correo" name="correo" required="required">
              
          </div>
          <div class="form-group ">
              
<center>
            <button id="recuperar" type="button" class="btn btn-primary btn-sm">RECUPERAR CUENTA</button>

            <button onclick="javascript:history.back()" class="btn btn-primary btn-sm">REGRESAR</button>
        </center>      
          </div>
           

       </div> 

          