<div class="col-xs-12">

<div class="alert-danger title-aviso title1"> <h4 class="title-termino"><center> <b> Bienvenido a OrienteX </b></center> </h4></div>

    <div class="row">
   
	<div class="col-md-10 col-md-offset-1 ">
	<h4 class="texto-top30"><center> <b> OrienteX.com.ve es un sitio exclusivamente dedicado a la publicidad para mayores de 18 años. <br> Este sitio estara online en: <br> 
	</b></center></h4>


	<div class="col-md-5 col-md-offset-4">
		<table >
		<tr>
		<td style="width: 76px; text-align: center;"><strong>Days</strong></td>
		<td style="width: 88px; text-align: center;"><strong>Hours</strong></td>
		<td style="width: 70px; text-align: center;"><strong>Minutes</strong></td>
		<td style="width: 90px; text-align: center;"><strong>Seconds</strong></td>
		</tr>
		<tr>
		<td colspan="4">
			
		<div id="box1"></div>

		</td>
		</tr>
		</table>

	</div>

	

			</div>
			</div>
              
    
        



</div>




