<?php echo $retVal = (isset($this->_error)) ? ' <div class="col-md-6 col-md-offset-3 alert alert-danger" role="alert"> <center>'.$this->_error.' <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </center> </div>' : "" ; ?>  
<div class="col-md-4 col-offset-md-4"> 
    <form action="<?php echo BASE_URL?>login" method="post" autocomplete="off" class="full-box logInForm">
        <input type="hidden" value="1" name="enviar" />   
    <p class="text-center text-muted"><i class="zmdi zmdi-account-circle zmdi-hc-5x"></i></p>
    <p class="text-center text-muted text-uppercase">Inicia sesión con tu cuenta</p>
    <div class="form-group label-floating">
      <label class="control-label" for="UserEmail">Usuario</label>
      <input class="form-control" id="usuario" name="usuario" type="text">
      <p class="help-block">Escribe tú usuario</p>
    </div>
    <div class="form-group label-floating">
      <label class="control-label" for="UserPass">Contraseña</label>
      <input class="form-control" id="clave" name="clave" type="password">
      <p class="help-block">Escribe tú contraseña</p>
    </div>

    <div id="empresa_botton" class="form-group text-center">
      <input type="submit" value="Entrar" id=entrar class="btn btn-raised btn-danger">
    </div>
  </form>
  </div>
