<div class="col-md-12">
<div class="col-md-6 col-md-offset-3"> <center> <h3> Bienvenidos al Sistema de Soporte Tecnico de Cotedem. </h3></center></div>
		
<div class="col-md-12"> 
<center> <a href="<?php BASE_URL ?>servicio" data-toggle='tooltip' data-placement='bottom' title='Pedir Soporte Tecnico'> <img width="50%" height="50%" src="<?php BASE_URL ?>public/img/soportetecnico.png"> </a><center></div>

	</div>
		
		
		

