<div class="col-md-12">
<div class="col-md-6 col-md-offset-3"> <center> <h3> <b>Bienvenidos al Sistema de Soporte Técnico de Cotedem.</b> </h3></center></div>
		
<div class="col-md-12"> 
<center> <a href="<?php BASE_URL ?>servicio" data-toggle='tooltip' data-placement='bottom' title='Pedir Soporte Tecnico'> <img width="40%" height="40%" src="<?php BASE_URL ?>public/img/soportetecnico.png"> </a><center></div>
	
<div class="col-md-12"> 
<center> <h4><b>Pasos para solicitar su soporte técnico:</b></h4><center></div>
	<div class="col-md-12"> 
<center>  <img width="85%" height="50%" src="<?php BASE_URL ?>public/img/pasos.png"><center></div>
	</div>